config/routes.rb
Blog::Application.routes.draw do
 root to: "sessions#new"
  
  resources :posts
  resources :identities
  match "/auth/failure", to: "sessions#failure"
  match "/signout", to: "sessions#destroy", :as => "signout"

  match 'auth/facebook/callback', to: 'sessions#create'
  match "/auth/:provider/callback" => "sessions#create"

  match "register" => "identities#new", :as => :register
  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy"

   

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  has_secure_password
  before_save { |identity| identity.email = email.downcase }

  attr_accessible :email, :name, :user_type, :password_digest, :password, :password_confirmation

  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :article, :comments, :image, :title
end

app/models/user.rb
class User < ActiveRecord::Base
		 attr_accessible :email, :first_name, :last_name, :country, :date_of_birth, :user_type, :address, :phone_number,
                  :skype, :chat, :facebook, :linkedin, :twitter, :nationality, :gender, :tagline, :avatar, :password,:employer, :employer_website,
                  :uid, :provider, :password_digest, :credits, :resume_viewing_until, :status_newsletter
 
  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery
 helper_method :current_user
private

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end 

  def project
    redirect_to root_path	unless current_user

  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def new
    @identity = env['omniauth.identity']
   
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_filter :project  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :current_user
  def new
   
    
  end

  def create
    @user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = @user.id

    redirect_to posts_path, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def failure
    # redirect url(:sessions, :new)
    redirect_to root_url, alert: "Authentication failed, please try again."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/identities/new.html.erb
<%= form_tag "/auth/identity/register" do %>
  <% if @identity && @identity.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name, @identity.try(:name) %>
  </div>
  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email, @identity.try(:email) %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %><br>
    <%= password_field_tag :password_confirmation %>
  </div>
  <div class="actions"><%= submit_tag "Register" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner ">
<ul class="nav nav-pills">
    <a class="brand" href="#">Title</a>
</ul>

    <form class="navbar-search right">
      <input type="text" class="search-query" placeholder="Search">
    </form>

   <ul class="nav pull-right">
    
     <div id="user_nav ">
<p id="demo"></p>
   <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %> 
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook"%>
      <% end %>
    </div>
  </div>
   </div>
  </div>
  <p id="ademo">
   JavaScript can change the content of an HTML element.
</p>
  <p id="demo"></p>
<%=  yield%>
<div id="coordinates_map">
  <button onclick="Test()">See your area map</button>
  </div>
<div id="slider">
  
 <!--  <a href="#link"><%= image_tag("arvind.JPG")%></a>
  <a href="#link"><%= image_tag ("arv.jpg")%></a>
  <a href="#link"><%= image_tag ("bootstrap-mdo-sfmoma-02.jpg")%></a>
  
   -->

<video width="320" height="240" controls>
  <source src="http://www.youtube.com/watch?v=WLXkcfvc4Lk" type="video/mp4">
  <source src="http://www.youtube.com/watch?v=WLXkcfvc4Lk" type="video/ogg">
  Your browser does not support the video tag.
</video>
</div>
<p id="coordinates">Click the button to get your coordinates:</p>
<button onclick="getLocation()">Find your coordinates</button>
<button onclick= "removeLocation()">Clean Locatin</button>

<img id="myimage" onclick="changeImage()"
src="assets/pic_bulboff.gif" width="100" height="180">
<p id = "location"><p>

</body>
<script "text/coffeescript">

</script>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :article %><br />
    <%= f.text_area :article %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Article</th>
    <th>Image</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.article %></td>
    <td><%= post.image %></td>
    <td><%= post.comments %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Article:</b>
  <%= @post.article %>
</p>

<p>
  <b>Image:</b>
  <%= @post.image %>
</p>

<p>
  <b>Comments:</b>
  <%= @post.comments %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>